"""Baseline schema: all 22 tables of implementation plan section 4.2.

A full baseline, not an empty Alembic init. Every table the design names exists
from the first migration, including the ones whose *behaviour* waits on an open
question, because a column that arrives later is a migration while a column that
is simply unused is not:

* `anonymous_sessions.expires_at` and `claimed_*` are unwritten until Phase 5.
  `OPEN-17` decides anonymous-session semantics; the identity half needs no
  decision and is built now (section 8).
* `claims.confidence` and `confidence_inputs` stay empty until Phase 2.
  `OPEN-14` decides the scale.
* `upload_chunks` carries no embedding column. Whether document retrieval needs
  vector search is `OPEN-12`, and pgvector is an infrastructure commitment that
  must not be made accidentally by a baseline migration.

Three hand edits to the autogenerated output, each marked below: the `citext`
extension, the deferred `research_sessions.current_version_id` foreign key, and
dropping the native enum types on downgrade.

Revision ID: 0001
Revises:
Created: 2026-09-10
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

_ENUM_TYPES = (
    "accessibility",
    "activity_status",
    "authority_tier",
    "claim_type",
    "conflict_cause",
    "conflict_status",
    "evidence_role",
    "export_format",
    "export_status",
    "export_theme",
    "message_role",
    "normalization_status",
    "research_status",
    "run_kind",
    "run_status",
    "source_category",
    "step_status",
    "termination_reason",
    "upload_state",
    "version_status",
    "viz_kind",
)

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `citext` backs users.email, so that two accounts cannot differ only in
    # capitalisation. IF NOT EXISTS because a preview database may be recycled.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('auth_ref', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], name=op.f('fk_anonymous_sessions_claimed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anonymous_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_anonymous_sessions_token_hash'))
    )
    op.create_table('research_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('anonymous_session_id', sa.Uuid(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('context_url', sa.Text(), nullable=True),
    sa.Column('context_company', sa.Text(), nullable=True),
    sa.Column('context_ticker', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('subject_interpretation_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'partial', 'failed', name='research_status'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls(owner_user_id, anonymous_session_id) = 1', name=op.f('ck_research_sessions_one_owner')),
    sa.ForeignKeyConstraint(['anonymous_session_id'], ['anonymous_sessions.id'], name=op.f('fk_research_sessions_anonymous_session_id_anonymous_sessions')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_research_sessions_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    op.create_index('ix_research_sessions_anonymous_session_id', 'research_sessions', ['anonymous_session_id'], unique=False)
    op.create_index('ix_research_sessions_owner_user_id_updated_at', 'research_sessions', ['owner_user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('research_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('building', 'complete', 'partial', 'failed', name='version_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['previous_version_id'], ['research_versions.id'], name=op.f('fk_research_versions_previous_version_id_research_versions')),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_research_versions_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_versions')),
    sa.UniqueConstraint('session_id', 'version_number', name=op.f('uq_research_versions_session_id_version_number'))
    )
    op.create_index('ix_research_versions_session_id', 'research_versions', ['session_id'], unique=False)

    # research_sessions.current_version_id and research_versions.session_id
    # reference each other, so one direction has to be added after both tables
    # exist. The model declares it `use_alter=True`; op.create_table does not
    # honour that, so it is added explicitly here.
    op.create_foreign_key(
        'fk_research_sessions_current_version_id_research_versions',
        'research_sessions', 'research_versions',
        ['current_version_id'], ['id'],
    )
    op.create_table('uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('processing_state', sa.Enum('pending', 'processing', 'ready', 'failed', name='upload_state'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_uploads_session_id_research_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index('ix_uploads_session_id', 'uploads', ['session_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('tool_category', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'complete', 'failed', name='activity_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_activity_events_session_id_research_sessions')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_activity_events_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events')),
    sa.UniqueConstraint('session_id', 'seq', name=op.f('uq_activity_events_session_id_seq'))
    )
    op.create_index('ix_activity_events_version_id', 'activity_events', ['version_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'agent', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_conversation_messages_session_id_research_sessions')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_conversation_messages_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('session_id', 'seq', name=op.f('uq_conversation_messages_session_id_seq'))
    )
    op.create_index('ix_conversation_messages_version_id', 'conversation_messages', ['version_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'pptx', name='export_format'), nullable=False),
    sa.Column('theme', sa.Enum('professional', 'investor', 'modern', 'corporate', 'minimal', 'dark', name='export_theme'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'ready', 'failed', name='export_status'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_exports_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    op.create_index('ix_exports_version_id', 'exports', ['version_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('is_executive_summary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_report_sections_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_sections')),
    sa.UniqueConstraint('version_id', 'ordering', name=op.f('uq_report_sections_version_id_ordering'))
    )
    op.create_index('ix_report_sections_version_id', 'report_sections', ['version_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('initial', 'update', 'conversation', name='run_kind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'partial', 'failed', name='run_status'), nullable=False),
    sa.Column('termination_reason', sa.Enum('sufficiency', 'ceiling', 'failure', name='termination_reason'), nullable=True),
    sa.Column('effort_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_research_runs_session_id_research_sessions')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_research_runs_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index('ix_research_runs_session_id', 'research_runs', ['session_id'], unique=False)
    op.create_index('ix_research_runs_version_id', 'research_runs', ['version_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_normalized', sa.Text(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('filing', 'financial', 'news', 'jobs', 'web', 'official', 'document', name='source_category'), nullable=False),
    sa.Column('authority_tier', sa.Enum('primary', 'secondary', 'lower', name='authority_tier'), nullable=False),
    sa.Column('tier_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accessibility', sa.Enum('accessible', 'paywalled', 'blocked', 'failed', name='accessibility'), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_sources_upload_id_uploads')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_sources_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('version_id', 'url_normalized', name=op.f('uq_sources_version_id_url_normalized'))
    )
    op.create_index('ix_sources_version_id', 'sources', ['version_id'], unique=False)
    op.create_table('upload_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_upload_chunks_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_chunks')),
    sa.UniqueConstraint('upload_id', 'ordinal', name=op.f('uq_upload_chunks_upload_id_ordinal'))
    )
    op.create_index('ix_upload_chunks_upload_id', 'upload_chunks', ['upload_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('fact', 'analysis', 'forecast', 'uncertainty', name='claim_type'), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('confidence_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("claim_type <> 'forecast' OR assumptions IS NOT NULL", name=op.f('ck_claims_forecast_needs_assumptions')),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], name=op.f('fk_claims_section_id_report_sections')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_claims_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_section_id', 'claims', ['section_id'], unique=False)
    op.create_index('ix_claims_version_id', 'claims', ['version_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('scale', sa.Numeric(), nullable=True),
    sa.Column('value_normalized', sa.Numeric(), nullable=True),
    sa.Column('normalization', sa.Enum('normalized', 'non_comparable', 'not_applicable', name='normalization_status'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('period_label', sa.Text(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_source_id_sources')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_evidence_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_source_id', 'evidence', ['source_id'], unique=False)
    op.create_index('ix_evidence_version_id', 'evidence', ['version_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', 'dead', name='step_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_run_steps_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_steps')),
    sa.UniqueConstraint('run_id', 'ordinal', name=op.f('uq_run_steps_run_id_ordinal'))
    )
    op.create_index('ix_run_steps_status_lease_expires_at', 'run_steps', ['status', 'lease_expires_at'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('tool_category', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_kind', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_digest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_tool_invocations_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocations'))
    )
    op.create_index('ix_tool_invocations_run_id', 'tool_invocations', ['run_id'], unique=False)
    op.create_table('visualizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('line', 'bar', 'table', 'matrix', 'metric', 'comparison', name='viz_kind'), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], name=op.f('fk_visualizations_section_id_report_sections')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_visualizations_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visualizations')),
    sa.UniqueConstraint('version_id', 'ordering', name=op.f('uq_visualizations_version_id_ordering'))
    )
    op.create_index('ix_visualizations_section_id', 'visualizations', ['section_id'], unique=False)
    op.create_index('ix_visualizations_version_id', 'visualizations', ['version_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('supporting', 'conflicting', name='evidence_role'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_claim_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id', 'role', name=op.f('pk_claim_evidence'))
    )
    op.create_index('ix_claim_evidence_evidence_id', 'claim_evidence', ['evidence_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('explained', 'unresolved', name='conflict_status'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_category', sa.Enum('period', 'definition', 'currency', 'estimate_vs_reported', 'methodology', 'staleness', name='conflict_cause'), nullable=True),
    sa.Column('tolerance_applied', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_conflicts_claim_id_claims')),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_conflicts_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts'))
    )
    op.create_index('ix_conflicts_claim_id', 'conflicts', ['claim_id'], unique=False)
    op.create_index('ix_conflicts_version_id', 'conflicts', ['version_id'], unique=False)
    op.create_table('message_evidence',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_message_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], name=op.f('fk_message_evidence_message_id_conversation_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'evidence_id', name=op.f('pk_message_evidence'))
    )
    op.create_index('ix_message_evidence_evidence_id', 'message_evidence', ['evidence_id'], unique=False)
    op.create_table('visualization_evidence',
    sa.Column('visualization_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_visualization_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualizations.id'], name=op.f('fk_visualization_evidence_visualization_id_visualizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visualization_id', 'evidence_id', name=op.f('pk_visualization_evidence'))
    )
    op.create_index('ix_visualization_evidence_evidence_id', 'visualization_evidence', ['evidence_id'], unique=False)
    op.create_table('conflict_evidence',
    sa.Column('conflict_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], name=op.f('fk_conflict_evidence_conflict_id_conflicts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_conflict_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conflict_id', 'evidence_id', name=op.f('pk_conflict_evidence'))
    )
    op.create_index('ix_conflict_evidence_evidence_id', 'conflict_evidence', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Break the research_sessions <-> research_versions cycle before dropping
    # either table.
    op.drop_constraint(
        'fk_research_sessions_current_version_id_research_versions',
        'research_sessions',
        type_='foreignkey',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conflict_evidence_evidence_id', table_name='conflict_evidence')
    op.drop_table('conflict_evidence')
    op.drop_index('ix_visualization_evidence_evidence_id', table_name='visualization_evidence')
    op.drop_table('visualization_evidence')
    op.drop_index('ix_message_evidence_evidence_id', table_name='message_evidence')
    op.drop_table('message_evidence')
    op.drop_index('ix_conflicts_version_id', table_name='conflicts')
    op.drop_index('ix_conflicts_claim_id', table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index('ix_claim_evidence_evidence_id', table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index('ix_visualizations_version_id', table_name='visualizations')
    op.drop_index('ix_visualizations_section_id', table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_index('ix_tool_invocations_run_id', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index('ix_run_steps_status_lease_expires_at', table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index('ix_evidence_version_id', table_name='evidence')
    op.drop_index('ix_evidence_source_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_claims_version_id', table_name='claims')
    op.drop_index('ix_claims_section_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_upload_chunks_upload_id', table_name='upload_chunks')
    op.drop_table('upload_chunks')
    op.drop_index('ix_sources_version_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_research_runs_version_id', table_name='research_runs')
    op.drop_index('ix_research_runs_session_id', table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index('ix_report_sections_version_id', table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index('ix_exports_version_id', table_name='exports')
    op.drop_table('exports')
    op.drop_index('ix_conversation_messages_version_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_activity_events_version_id', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_uploads_session_id', table_name='uploads')
    op.drop_table('uploads')
    op.drop_index('ix_research_versions_session_id', table_name='research_versions')
    op.drop_table('research_versions')
    op.drop_index('ix_research_sessions_owner_user_id_updated_at', table_name='research_sessions')
    op.drop_index('ix_research_sessions_anonymous_session_id', table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_table('anonymous_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate tracks tables, not types: a native enum outlives every table
    # that used it, and the next upgrade then fails with "type already exists".
    for enum_name in _ENUM_TYPES:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)

    op.execute("DROP EXTENSION IF EXISTS citext")
