"""Planned questions become persisted rows.

The one schema consequence of `DEC-04`. Termination is defined as coverage of
the question set stage 2 plans, and `REQ-AGENT-005 AC-2` requires the criteria
to be inspectable after the run, so the questions cannot live in memory.

`question_evidence` records which evidence addresses which question: the
coverage count in `DEC-04 §3.2` is defined over sources yielding evidence that
addresses a question, and one extracted fact can answer more than one.

Revision ID: 0002
Revises: 0001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('area_name', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('resolution_state', sa.Enum('open', 'resolved', 'unanswerable', name='question_state'), nullable=False),
    sa.Column('tool_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unanswerable_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['research_versions.id'], name=op.f('fk_research_questions_version_id_research_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_questions')),
    sa.UniqueConstraint('version_id', 'ordering', name=op.f('uq_research_questions_version_id_ordering'))
    )
    op.create_index('ix_research_questions_version_id', 'research_questions', ['version_id'], unique=False)
    op.create_index('ix_research_questions_version_id_resolution_state', 'research_questions', ['version_id', 'resolution_state'], unique=False)
    op.create_table('question_evidence',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_question_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['research_questions.id'], name=op.f('fk_question_evidence_question_id_research_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'evidence_id', name=op.f('pk_question_evidence'))
    )
    op.create_index('ix_question_evidence_evidence_id', 'question_evidence', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_evidence_evidence_id', table_name='question_evidence')
    op.drop_table('question_evidence')
    op.drop_index('ix_research_questions_version_id_resolution_state', table_name='research_questions')
    op.drop_index('ix_research_questions_version_id', table_name='research_questions')
    op.drop_table('research_questions')
    # ### end Alembic commands ###

    # Autogenerate tracks tables, not types: the enum outlives the table that
    # used it, and the next upgrade then fails with "type already exists".
    sa.Enum(name="question_state").drop(op.get_bind(), checkfirst=True)
