"""Accounts, anonymous expiry, and deletion (`DEC-16`, `DEC-17`, `DEC-18`).

`DEC-16` makes accounts first-party: `users.password_hash` holds an Argon2id
hash and `user_sessions` holds the SHA-256 of each session token. `DEC-17` gives
anonymous sessions a lifetime, so existing rows are backfilled to expire 30 days
after their last activity rather than being left to live forever on a null.
`DEC-18` hard-deletes research, and the purge that does it finds its work
through the new index on `research_sessions.deleted_at`.

`rate_limit_counters` is Postgres rather than process memory because the API
runs as many instances, and a limit each instance counts separately limits
nothing (`REQ-AUTH-009 AC-3`).

Revision ID: 0005
Revises: 0004
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start', name=op.f('pk_rate_limit_counters'))
    )
    op.create_index('ix_rate_limit_counters_window_start', 'rate_limit_counters', ['window_start'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_anonymous_sessions_expires_at', 'anonymous_sessions', ['expires_at'], unique=False)
    op.create_index('ix_research_sessions_deleted_at', 'research_sessions', ['deleted_at'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # `DEC-17`: a session with no expiry would outlive the decision that gave
    # sessions one. Backfilled from last activity, the same rule new rows get.
    op.execute(
        "UPDATE anonymous_sessions SET expires_at = last_seen_at + interval '30 days' "
        "WHERE expires_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_index('ix_research_sessions_deleted_at', table_name='research_sessions')
    op.drop_index('ix_anonymous_sessions_expires_at', table_name='anonymous_sessions')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_rate_limit_counters_window_start', table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
