/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Deliberately does not touch the database: a health
         *     check that fails when Postgres blips takes the API down with it.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Research
         * @description Start research. **202**, because the answer does not exist yet.
         *
         *     The response is committed rows and nothing else: the run is picked up by
         *     whatever is polling `run_steps`, which is what keeps `OPEN-03` a hosting
         *     question (implementation plan §5.6).
         */
        post: operations["create_research_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Research
         * @description The session header the workspace renders around (`REQ-WORK-002`).
         */
        get: operations["get_research_v1_research__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Events newer than `after` (`REQ-ACT-001`, implementation plan §6.3).
         *
         *     Phase 1 ships polling. Phase 3 gives this same route a streaming content
         *     type; because `seq` is already the resume key, that changes no schema, no
         *     route and no client state model.
         */
        get: operations["get_activity_v1_research__session_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/versions/{version_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description One version, denormalised into a single response (`NFR-PERF-004`).
         */
        get: operations["get_version_v1_research__session_id__versions__version_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEventOut
         * @description One timeline entry. User-facing text only (`REQ-ACT-003`).
         */
        ActivityEventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Label */
            label: string;
            /** Seq */
            seq: number;
            status: components["schemas"]["ActivityStatus"];
            /** Tool Category */
            tool_category: string | null;
        };
        /**
         * ActivityPage
         * @description Events after a sequence number, plus where to resume from.
         *
         *     `next_after` is what the client sends back, so the polling loop never has to
         *     reason about timestamps — and the Phase 3 SSE upgrade resumes from exactly
         *     the same value (implementation plan §6.3).
         */
        ActivityPage: {
            /** Events */
            events: components["schemas"]["ActivityEventOut"][];
            /** Next After */
            next_after: number;
        };
        /**
         * ActivityStatus
         * @description Per-event status in the activity timeline (`REQ-ACT-004 AC-2`).
         * @enum {string}
         */
        ActivityStatus: "in_progress" | "complete" | "failed";
        /**
         * AuthorityTier
         * @description Source authority (`REQ-EVID-002`). Assignment rules are `OPEN-15`.
         * @enum {string}
         */
        AuthorityTier: "primary" | "secondary" | "lower";
        /**
         * ClaimOut
         * @description One assertion, typed, with the sources behind it (`REQ-SYNTH-002..003`).
         */
        ClaimOut: {
            claim_type: components["schemas"]["ClaimType"];
            /** Confidence */
            confidence: string | null;
            /** Confidence Rationale */
            confidence_rationale: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Important */
            is_important: boolean;
            /** Source Ids */
            source_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * ClaimType
         * @description Claim taxonomy (`REQ-SYNTH-002`).
         *
         *     The gate in `REQ-EVID-017 AC-1` is scoped to `FACT`, and
         *     `REQ-SYNTH-009` requires assumptions on `FORECAST`, so these two values are
         *     load-bearing rather than descriptive.
         * @enum {string}
         */
        ClaimType: "fact" | "analysis" | "forecast" | "uncertainty";
        /**
         * ConflictCause
         * @description Why two pieces of evidence disagree (`REQ-EVID-013 AC-1`).
         * @enum {string}
         */
        ConflictCause: "period" | "definition" | "currency" | "estimate_vs_reported" | "methodology" | "staleness";
        /**
         * ConflictOut
         * @description Evidence that disagrees, surfaced rather than resolved away.
         *
         *     `REQ-WORK-009`: conflicts are a visible feature of the report, not hidden.
         *     `explanation` is null when nothing in the evidence accounts for the gap,
         *     and `status` then reads `unresolved` — `REQ-EVID-013 AC-3` forbids
         *     inventing a cause, and `REQ-EVID-014` requires saying so plainly.
         */
        ConflictOut: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Explanation */
            explanation: string | null;
            explanation_category: components["schemas"]["ConflictCause"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sides */
            sides: components["schemas"]["ConflictSideOut"][];
            status: components["schemas"]["ConflictStatus"];
        };
        /**
         * ConflictSideOut
         * @description One value in a disagreement, with what a reader needs to judge it.
         *
         *     `REQ-EVID-012 AC-3` names the three: the source, its tier, and when it was
         *     read. Showing the values without them would present a disagreement the
         *     reader has no way to weigh.
         */
        ConflictSideOut: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Label */
            label: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Value */
            value: string;
        };
        /**
         * ConflictStatus
         * @description Whether a conflict was explained or is surfaced unresolved (`REQ-EVID-014`).
         * @enum {string}
         */
        ConflictStatus: "explained" | "unresolved";
        /**
         * CreateResearchRequest
         * @description `REQ-INPUT-001..005`. Only the objective is required.
         */
        CreateResearchRequest: {
            /** Context Company */
            context_company?: string | null;
            /** Context Ticker */
            context_ticker?: string | null;
            /** Context Url */
            context_url?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Objective */
            objective: string;
        };
        /**
         * CreateResearchResponse
         * @description 202: the work is accepted, not finished (`REQ-AGENT-008 AC-1`).
         */
        CreateResearchResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version Number */
            version_number: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ResearchSessionOut
         * @description The session header the workspace renders around (`REQ-WORK-002`).
         */
        ResearchSessionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Objective */
            objective: string;
            status: components["schemas"]["ResearchStatus"];
            /** Subject */
            subject: string | null;
            /** Subject Interpretation Note */
            subject_interpretation_note: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * ResearchStatus
         * @description Lifecycle of a research session.
         * @enum {string}
         */
        ResearchStatus: "pending" | "running" | "complete" | "partial" | "failed";
        /**
         * SectionOut
         * @description A report section and the claims it renders.
         */
        SectionOut: {
            /** Claim Ids */
            claim_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Executive Summary */
            is_executive_summary: boolean;
            /** Ordering */
            ordering: number;
            /** Title */
            title: string;
        };
        /**
         * SourceOut
         * @description Where a claim's evidence came from, and when it was read.
         *
         *     `retrieved_at` is on the wire because `REQ-EVID-004` makes it part of what
         *     the user is entitled to see, not internal bookkeeping.
         */
        SourceOut: {
            authority_tier: components["schemas"]["AuthorityTier"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Published At */
            published_at: string | null;
            /** Publisher */
            publisher: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Url */
            url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionOut
         * @description One whole version, in one response.
         */
        VersionOut: {
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Closed At */
            closed_at: string | null;
            /** Conflicts */
            conflicts: components["schemas"]["ConflictOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            status: components["schemas"]["VersionStatus"];
            /** Version Number */
            version_number: number;
        };
        /**
         * VersionStatus
         * @description Lifecycle of one immutable version (`REQ-VER-002`).
         * @enum {string}
         */
        VersionStatus: "building" | "complete" | "partial" | "failed";
        /**
         * VersionSummary
         * @description One entry in the version list (`REQ-VER-008`).
         */
        VersionSummary: {
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["VersionStatus"];
            /** Version Number */
            version_number: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_research_v1_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_v1_research__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_v1_research__session_id__activity_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_v1_research__session_id__versions__version_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                version_number: number;
            };
            cookie?: {
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
