/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Deliberately does not touch the database: a health
         *     check that fails when Postgres blips takes the API down with it.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session State
         * @description Who this browser is signed in as. Never a 401.
         */
        get: operations["get_session_state_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description Sign in, and bring this browser's anonymous research into the account.
         */
        post: operations["sign_in_v1_auth_signin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Out
         * @description Revoke this browser's account session. Idempotent.
         *
         *     Revoked in the database, not only cleared in the browser: a copy of the
         *     cookie taken before sign-out must stop working too.
         */
        post: operations["sign_out_v1_auth_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Up
         * @description Create an account, sign this browser in, and bring its research along.
         */
        post: operations["sign_up_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Export
         * @description One export; with a short-lived download link once it is ready.
         */
        get: operations["get_export_v1_exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Export
         * @description Render a failed export again, without re-running research (`NFR-REL-003`).
         */
        post: operations["retry_export_v1_exports__export_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description The account's research, most recently updated first.
         */
        get: operations["list_history_v1_me_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Research
         * @description Start research. **202**, because the answer does not exist yet.
         *
         *     The response is committed rows and nothing else: the run is picked up by
         *     whatever is polling `run_steps`, which is what keeps `OPEN-03` a hosting
         *     question (implementation plan §5.6).
         */
        post: operations["create_research_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Research
         * @description Attach this browser's anonymous research to the signed-in account.
         *
         *     For a visitor who researched while signed out and is already signed in on
         *     this browser. Needs both halves: an account to receive, and an anonymous
         *     session to give. With no anonymous session it moves nothing and says so.
         */
        post: operations["claim_research_v1_research_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Research
         * @description The session header the workspace renders around (`REQ-WORK-002`).
         */
        get: operations["get_research_v1_research__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Research Session
         * @description Delete research and everything produced for it (`REQ-SEC-008`, `DEC-18`).
         *
         *     Hidden and stopped in this request, its files removed from storage, and its
         *     rows purged by the worker's sweep once no step can still be writing them.
         *
         *     **Idempotent, and silent about what it could not find.** Research that is
         *     already gone and research that was never this caller's both answer 204:
         *     a 404 for one and not the other would let a guessed id be tested for
         *     existence (`REQ-SEC-009`).
         */
        delete: operations["delete_research_session_v1_research__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Events newer than `after` (`REQ-ACT-001`, implementation plan §6.3).
         *
         *     Phase 1 ships polling. Phase 3 gives this same route a streaming content
         *     type; because `seq` is already the resume key, that changes no schema, no
         *     route and no client state model.
         */
        get: operations["get_activity_v1_research__session_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description The conversation so far (`REQ-CONV-007 AC-2`).
         *
         *     Ownership-scoped like everything else: a conversation is about someone's
         *     research and `REQ-SEC-002` does not stop applying because the surface is a
         *     chat.
         */
        get: operations["get_messages_v1_research__session_id__messages_get"];
        put?: never;
        /**
         * Ask
         * @description Ask a follow-up, and answer it from the research (`REQ-CONV-001`).
         *
         *     Answered synchronously, unlike a research run. A question against evidence
         *     already gathered is one model call, and pushing it through `run_steps`
         *     would make the reader wait on a poll for something that takes a second.
         *
         *     **Follow-up research is the exception, and it is deliberately not done
         *     here.** `REQ-CONV-003` requires fresh retrieval when the evidence is
         *     insufficient, and retrieval belongs to the pipeline — it needs the budget,
         *     the tool registry, the termination gate and the activity stream, none of
         *     which a request handler should own. So the intent is classified, the answer
         *     says plainly that new research is needed, and enqueuing that run is the
         *     next piece of work. Answering "I researched that" without having done so
         *     would be the one thing this product must never do.
         */
        post: operations["ask_v1_research__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Research
         * @description Enqueue the run for a session created with `defer_start`.
         *
         *     **Idempotent.** A session that already has a run is returned unchanged
         *     rather than given a second one: this is the call a client retries after a
         *     dropped connection, and two runs against one version would produce two sets
         *     of claims in the same report.
         */
        post: operations["start_research_v1_research__session_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Research
         * @description Update Research: fresh retrieval into a new version (`REQ-VER-001`, `REQ-VER-005`).
         *
         *     **Only ever from this request.** Nothing schedules it and nothing retries it
         *     on a timer (`REQ-VER-009`); a reader pressing the control is the only thing
         *     that reaches this line.
         *
         *     **Refused while research is already running**, because two runs would open
         *     two versions against one baseline and race to be current. Refused, too,
         *     when there is no completed version to update: an update is measured against
         *     a report, and a failed first run produced none.
         *
         *     The previous version is untouched by any of this (`REQ-VER-002`): the new
         *     version gets its own sources, evidence and retrieval timestamps, and the
         *     session's current pointer moves while every earlier version stays readable.
         */
        post: operations["update_research_v1_research__session_id__update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Uploads
         * @description Every file attached to this session, with its processing state.
         *
         *     This is what `REQ-DOC-003 AC-1` is rendered from. Polled by the intake
         *     panel while anything is still processing, which is why it is cheap: one
         *     indexed query and a count per row.
         */
        get: operations["list_uploads_v1_research__session_id__uploads_get"];
        put?: never;
        /**
         * Create Upload Ticket
         * @description Reserve a slot and sign a URL for one file.
         *
         *     **201, not 200**: this creates the `uploads` row. The row exists before the
         *     bytes do, which is what lets the count limit hold — a client that presigns
         *     ten tickets and uploads none has used its ten.
         */
        post: operations["create_upload_ticket_v1_research__session_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Upload
         * @description Remove a file and its extracted text (`REQ-SEC-008 AC-2`).
         *
         *     The chunks go with the row, immediately: they are the searchable copy, and
         *     a deleted document that can still be retrieved as evidence is not deleted.
         *     The object is removed next. If storage refuses, the row still goes — the
         *     user's instruction is honoured and the orphaned object is a cleanup
         *     problem, not a privacy one that waits on a retry.
         */
        delete: operations["delete_upload_v1_research__session_id__uploads__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Confirm the bytes arrived, and queue the file for reading.
         *
         *     The size is read back from storage and re-checked, which is the second half
         *     of `REQ-DOC-010 AC-1`. A file that is over the limit — or that never
         *     arrived — leaves no usable row behind.
         */
        post: operations["complete_upload_v1_research__session_id__uploads__upload_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/versions/{version_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description One version, denormalised into a single response (`NFR-PERF-004`).
         */
        get: operations["get_version_v1_research__session_id__versions__version_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{session_id}/versions/{version_number}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exports
         * @description Every export of one version, newest first (export version tracking).
         */
        get: operations["list_exports_v1_research__session_id__versions__version_number__exports_get"];
        put?: never;
        /**
         * Request Export
         * @description Queue a PDF or PowerPoint of one version in one theme.
         *
         *     Asking again for the same version, format and theme returns the export
         *     already queued or ready rather than rendering it twice: the version cannot
         *     change, so neither can the file.
         */
        post: operations["request_export_v1_research__session_id__versions__version_number__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountOut
         * @description The signed-in account, as the account itself may see it.
         */
        AccountOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
        };
        /**
         * ActivityEventOut
         * @description One timeline entry. User-facing text only (`REQ-ACT-003`).
         */
        ActivityEventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Label */
            label: string;
            /** Seq */
            seq: number;
            status: components["schemas"]["ActivityStatus"];
            /** Tool Category */
            tool_category: string | null;
        };
        /**
         * ActivityPage
         * @description Events after a sequence number, plus where to resume from.
         *
         *     `next_after` is what the client sends back, so the polling loop never has to
         *     reason about timestamps — and the Phase 3 SSE upgrade resumes from exactly
         *     the same value (implementation plan §6.3).
         */
        ActivityPage: {
            /** Events */
            events: components["schemas"]["ActivityEventOut"][];
            /** Next After */
            next_after: number;
        };
        /**
         * ActivityStatus
         * @description Per-event status in the activity timeline (`REQ-ACT-004 AC-2`).
         * @enum {string}
         */
        ActivityStatus: "in_progress" | "complete" | "failed";
        /**
         * AskIn
         * @description A follow-up question.
         */
        AskIn: {
            /** Context Ref */
            context_ref?: {
                [key: string]: string;
            } | null;
            /** Question */
            question: string;
        };
        /**
         * AskOut
         * @description The turn pair a question produces.
         */
        AskOut: {
            answer: components["schemas"]["MessageOut"];
            question: components["schemas"]["MessageOut"];
            /** Researched */
            researched: boolean;
        };
        /**
         * AuthOut
         * @description The outcome of signing up or signing in.
         */
        AuthOut: {
            account: components["schemas"]["AccountOut"];
            /** Claimed */
            claimed: number;
        };
        /**
         * AuthorityTier
         * @description Source authority (`REQ-EVID-002`). Assignment rules are `OPEN-15`.
         * @enum {string}
         */
        AuthorityTier: "primary" | "secondary" | "lower";
        /**
         * ChangeCategory
         * @description The masterplan's kinds of change (`REQ-VER-006 AC-2`), plus a remainder.
         * @enum {string}
         */
        ChangeCategory: "financial_figures" | "stock_information" | "job_postings" | "new_products" | "new_competitors" | "forecast_assumptions" | "other";
        /** ChangeCountsOut */
        ChangeCountsOut: {
            /** New Sources */
            new_sources: number;
            /** Unchanged */
            unchanged: number;
        };
        /**
         * ChangeKind
         * @description The closed set of changes `DEC-20` recognises. Order is display order.
         * @enum {string}
         */
        ChangeKind: "conclusion_changed" | "figure_changed" | "newer_period" | "assumptions_changed" | "new_finding" | "gap_closed" | "gap_opened" | "no_longer_found";
        /**
         * ChangeOut
         * @description One meaningful difference from the previous version (`DEC-20`).
         */
        ChangeOut: {
            after: components["schemas"]["ChangeSideOut"] | null;
            before: components["schemas"]["ChangeSideOut"] | null;
            category: components["schemas"]["ChangeCategory"];
            confidence_change: components["schemas"]["ConfidenceChangeOut"] | null;
            /** Evidence Ids */
            evidence_ids: string[];
            kind: components["schemas"]["ChangeKind"];
            /** Summary */
            summary: string;
        };
        /**
         * ChangeSideOut
         * @description One side of a change: the claim as it stood in one version.
         */
        ChangeSideOut: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            claim_type: components["schemas"]["ClaimType"];
            /** Confidence */
            confidence: string | null;
            /** Period */
            period: string | null;
            /** Text */
            text: string;
            /** Value */
            value: string | null;
        };
        /**
         * ChangeSummaryOut
         * @description What's Changed (`REQ-VER-006`). Null on a first version.
         *
         *     `available` is false when the comparison could not be made; the report is
         *     still complete, and the workspace says the summary is missing rather than
         *     implying nothing changed.
         */
        ChangeSummaryOut: {
            /** Available */
            available: boolean;
            /** Changes */
            changes?: components["schemas"]["ChangeOut"][];
            compared_with: components["schemas"]["ComparedVersionOut"];
            counts?: components["schemas"]["ChangeCountsOut"] | null;
            /**
             * Has Changes
             * @default false
             */
            has_changes: boolean;
            /**
             * Headline
             * @default
             */
            headline: string;
        };
        /**
         * ClaimOut
         * @description One assertion, typed, with the sources behind it (`REQ-SYNTH-002..003`).
         */
        ClaimOut: {
            claim_type: components["schemas"]["ClaimType"];
            /** Confidence */
            confidence: string | null;
            /** Confidence Rationale */
            confidence_rationale: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Important */
            is_important: boolean;
            /** Reporting Period */
            reporting_period: string | null;
            /** Source Ids */
            source_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * ClaimType
         * @description Claim taxonomy (`REQ-SYNTH-002`).
         *
         *     The gate in `REQ-EVID-017 AC-1` is scoped to `FACT`, and
         *     `REQ-SYNTH-009` requires assumptions on `FORECAST`, so these two values are
         *     load-bearing rather than descriptive.
         * @enum {string}
         */
        ClaimType: "fact" | "analysis" | "forecast" | "uncertainty";
        /** ComparedVersionOut */
        ComparedVersionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * ConfidenceChangeOut
         * @description `REQ-VER-007 AC-3`: a confidence change is stated with the conclusion.
         */
        ConfidenceChangeOut: {
            /** From */
            from: string | null;
            /** To */
            to: string | null;
        };
        /**
         * ConflictCause
         * @description Why two pieces of evidence disagree (`REQ-EVID-013 AC-1`).
         * @enum {string}
         */
        ConflictCause: "period" | "definition" | "currency" | "estimate_vs_reported" | "methodology" | "staleness";
        /**
         * ConflictOut
         * @description Evidence that disagrees, surfaced rather than resolved away.
         *
         *     `REQ-WORK-009`: conflicts are a visible feature of the report, not hidden.
         *     `explanation` is null when nothing in the evidence accounts for the gap,
         *     and `status` then reads `unresolved` — `REQ-EVID-013 AC-3` forbids
         *     inventing a cause, and `REQ-EVID-014` requires saying so plainly.
         */
        ConflictOut: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Explanation */
            explanation: string | null;
            explanation_category: components["schemas"]["ConflictCause"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sides */
            sides: components["schemas"]["ConflictSideOut"][];
            status: components["schemas"]["ConflictStatus"];
        };
        /**
         * ConflictSideOut
         * @description One value in a disagreement, with what a reader needs to judge it.
         *
         *     `REQ-EVID-012 AC-3` names the three: the source, its tier, and when it was
         *     read. Showing the values without them would present a disagreement the
         *     reader has no way to weigh.
         */
        ConflictSideOut: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** From Your Document */
            from_your_document: boolean;
            /** Label */
            label: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /** Value */
            value: string;
        };
        /**
         * ConflictStatus
         * @description Whether a conflict was explained or is surfaced unresolved (`REQ-EVID-014`).
         * @enum {string}
         */
        ConflictStatus: "explained" | "unresolved";
        /**
         * CreateResearchRequest
         * @description `REQ-INPUT-001..005`. Only the objective is required.
         */
        CreateResearchRequest: {
            /** Context Company */
            context_company?: string | null;
            /** Context Ticker */
            context_ticker?: string | null;
            /** Context Url */
            context_url?: string | null;
            /**
             * Defer Start
             * @default false
             */
            defer_start: boolean;
            /** Instructions */
            instructions?: string | null;
            /** Objective */
            objective: string;
        };
        /**
         * CreateResearchResponse
         * @description 202: the work is accepted, not finished (`REQ-AGENT-008 AC-1`).
         */
        CreateResearchResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CredentialsIn
         * @description An email and password, for signing up or signing in.
         *
         *     Bounds here are only what keeps the request sane. The password rule
         *     itself (`DEC-16`) is checked by the route, so a too-short password gets a
         *     message saying what the rule is rather than a generic validation failure.
         */
        CredentialsIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * EvidenceOut
         * @description One piece of evidence behind a claim, as the inspector shows it.
         *
         *     `REQ-EVID-019 AC-1` names what inspection must show, and "the relevant
         *     evidence" is the item the payload did not carry: source, tier and retrieval
         *     time were all reachable through `source_ids`, but the *excerpt* — the words
         *     the source actually printed — existed only in the database.
         *
         *     That excerpt is the whole point of the citation surface. A reader checking
         *     a claim is checking it against what was written, not against a link.
         */
        EvidenceOut: {
            /** Excerpt */
            excerpt: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reporting Period */
            reporting_period: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Statement */
            statement: string;
            /** Value Raw */
            value_raw: string | null;
        };
        /**
         * ExportFormat
         * @description Export formats (`REQ-EXP-001`, `REQ-EXP-002`).
         * @enum {string}
         */
        ExportFormat: "pdf" | "pptx";
        /**
         * ExportOut
         * @description One export and where it stands (`REQ-EXP-006`, `REQ-EXP-007 AC-2`).
         */
        ExportOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Download Url */
            download_url?: string | null;
            /** Error */
            error: string | null;
            format: components["schemas"]["ExportFormat"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["ExportStatus"];
            theme: components["schemas"]["ExportTheme"];
            /** Version Number */
            version_number: number;
        };
        /**
         * ExportRequest
         * @description Which format, in which of the six themes (`REQ-EXP-003`).
         */
        ExportRequest: {
            format: components["schemas"]["ExportFormat"];
            theme: components["schemas"]["ExportTheme"];
        };
        /**
         * ExportStatus
         * @description Export job lifecycle. Retryable without re-running research (`NFR-REL-003`).
         * @enum {string}
         */
        ExportStatus: "pending" | "running" | "ready" | "failed";
        /**
         * ExportTheme
         * @description The six predefined themes (`REQ-EXP-003`). Visual definitions are `OPEN-22`.
         * @enum {string}
         */
        ExportTheme: "professional" | "investor" | "modern" | "corporate" | "minimal" | "dark";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItemOut
         * @description One saved research session in the history list (`REQ-AUTH-005 AC-1`).
         */
        HistoryItemOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Objective */
            objective: string;
            status: components["schemas"]["ResearchStatus"];
            /** Subject */
            subject: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Count */
            version_count: number;
        };
        /**
         * MessageOut
         * @description One conversation turn (`REQ-CONV-007`).
         */
        MessageOut: {
            claim_type: components["schemas"]["ClaimType"] | null;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["MessageRole"];
            /** Seq */
            seq: number;
        };
        /**
         * MessageRole
         * @description Author of a conversation message (`REQ-CONV-007`).
         * @enum {string}
         */
        MessageRole: "user" | "agent";
        /**
         * OwnershipClaimOut
         * @description What claiming anonymous research moved (`REQ-AUTH-004`). Not to be
         *     confused with `ClaimOut`, an assertion in a report.
         */
        OwnershipClaimOut: {
            /** Claimed */
            claimed: number;
        };
        /**
         * ResearchSessionOut
         * @description The session header the workspace renders around (`REQ-WORK-002`).
         */
        ResearchSessionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Objective */
            objective: string;
            status: components["schemas"]["ResearchStatus"];
            /** Subject */
            subject: string | null;
            /** Subject Interpretation Note */
            subject_interpretation_note: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * ResearchStatus
         * @description Lifecycle of a research session.
         * @enum {string}
         */
        ResearchStatus: "pending" | "running" | "complete" | "partial" | "failed";
        /**
         * RunKind
         * @description Which job produced this run (implementation plan §7.1).
         * @enum {string}
         */
        RunKind: "initial" | "update" | "conversation";
        /**
         * SectionOut
         * @description A report section and the claims it renders.
         */
        SectionOut: {
            /** Claim Ids */
            claim_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Executive Summary */
            is_executive_summary: boolean;
            /** Ordering */
            ordering: number;
            /** Title */
            title: string;
        };
        /**
         * SessionStateOut
         * @description Who this browser is signed in as, if anyone.
         *
         *     A 200 with `account: null` rather than a 401, because "not signed in" is
         *     the ordinary state of most visitors and not an error to log in a console.
         */
        SessionStateOut: {
            account: components["schemas"]["AccountOut"] | null;
        };
        /**
         * SourceCategory
         * @description Which tool category produced the source (`REQ-TOOL-002..007`).
         * @enum {string}
         */
        SourceCategory: "filing" | "financial" | "news" | "jobs" | "web" | "official" | "document";
        /**
         * SourceOut
         * @description Where a claim's evidence came from, and when it was read.
         *
         *     `retrieved_at` is on the wire because `REQ-EVID-004` makes it part of what
         *     the user is entitled to see, not internal bookkeeping.
         */
        SourceOut: {
            authority_tier: components["schemas"]["AuthorityTier"];
            category: components["schemas"]["SourceCategory"];
            /**
             * Document Removed
             * @default false
             */
            document_removed: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Published At */
            published_at: string | null;
            /** Publisher */
            publisher: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Upload Id */
            upload_id?: string | null;
            /** Url */
            url: string | null;
        };
        /**
         * UploadOut
         * @description One attached file as the intake panel shows it (`REQ-DOC-003`).
         */
        UploadOut: {
            /** Chunk Count */
            chunk_count: number;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Size Bytes */
            size_bytes: number;
            state: components["schemas"]["UploadState"];
        };
        /**
         * UploadState
         * @description Document processing lifecycle (`REQ-DOC-003..004`).
         * @enum {string}
         */
        UploadState: "pending" | "processing" | "ready" | "failed";
        /**
         * UploadTicket
         * @description Where to PUT the bytes, and until when.
         *
         *     The URL is a short-lived write grant to one key (`DEC-12`). The API never
         *     sees the file: the browser uploads directly, which is implementation plan
         *     §10 and the reason a 25 MB file does not have to fit through a request
         *     handler.
         */
        UploadTicket: {
            /** Content Type */
            content_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Url */
            url: string;
        };
        /**
         * UploadTicketRequest
         * @description Ask for permission to upload one file.
         *
         *     The size is what the *client* says it is. It is checked here so an
         *     oversized file is refused before it is transferred rather than after
         *     (`REQ-DOC-010 AC-2`), and checked again at completion against the object
         *     that actually arrived, because a declared size is not a limit.
         */
        UploadTicketRequest: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionOut
         * @description One whole version, in one response.
         */
        VersionOut: {
            change_summary?: components["schemas"]["ChangeSummaryOut"] | null;
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Closed At */
            closed_at: string | null;
            /** Conflicts */
            conflicts: components["schemas"]["ConflictOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            origin?: components["schemas"]["RunKind"] | null;
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            status: components["schemas"]["VersionStatus"];
            /** Version Number */
            version_number: number;
            /** Visualizations */
            visualizations: components["schemas"]["VisualizationOut"][];
        };
        /**
         * VersionStatus
         * @description Lifecycle of one immutable version (`REQ-VER-002`).
         * @enum {string}
         */
        VersionStatus: "building" | "complete" | "partial" | "failed";
        /**
         * VersionSummary
         * @description One entry in the version list (`REQ-VER-008`).
         */
        VersionSummary: {
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            origin?: components["schemas"]["RunKind"] | null;
            status: components["schemas"]["VersionStatus"];
            /** Version Number */
            version_number: number;
        };
        /**
         * VisualizationOut
         * @description A chart or table, as a spec the client renders (`DEC-11`).
         */
        VisualizationOut: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["VizKind"];
            /** Ordering */
            ordering: number;
            /**
             * Section Id
             * Format: uuid
             */
            section_id: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /**
         * VizKind
         * @description Visualization forms (`REQ-VIZ-001`). The renderer is `OPEN-25`.
         * @enum {string}
         */
        VizKind: "line" | "bar" | "table" | "matrix" | "metric" | "comparison";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_session_state_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_v1_auth_signin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_v1_auth_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sign_up_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_v1_exports__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_export_v1_exports__export_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_v1_me_research_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_research_v1_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_research_v1_research_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_v1_research__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_research_session_v1_research__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_v1_research__session_id__activity_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_v1_research__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_v1_research__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_research_v1_research__session_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_research_v1_research__session_id__update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_uploads_v1_research__session_id__uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_ticket_v1_research__session_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_v1_research__session_id__uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                upload_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_v1_research__session_id__uploads__upload_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                upload_id: string;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_v1_research__session_id__versions__version_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                version_number: number;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_v1_research__session_id__versions__version_number__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                version_number: number;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_export_v1_research__session_id__versions__version_number__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                version_number: number;
            };
            cookie?: {
                scrapr_account?: string | null;
                scrapr_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
