"""Structural rules the schema must keep, checked without a database.

These are the invariants that are cheap to break and expensive to discover late:
a naive timestamp column, a version-scoped table missing its index, an enum
storing member names instead of values. Each is asserted against
`Base.metadata`, so a new model file inherits the whole set for free.
"""

from __future__ import annotations

import pytest
from sqlalchemy import DateTime, Enum, Table
from sqlalchemy.dialects import postgresql

from scrapr_core.db.base import NAMING_CONVENTION
from scrapr_core.db.enums import ClaimType, pg_enum
from scrapr_core.db.models import Base

METADATA = Base.metadata

# Everything the implementation plan section 4.1 scopes to a version rather than
# a session. `version_id` on each of these is what makes immutability structural
# instead of a discipline someone has to remember.
VERSION_SCOPED_TABLES = frozenset(
    {
        "sources",
        "evidence",
        "claims",
        "conflicts",
        "report_sections",
        "visualizations",
        "exports",
        "research_runs",
    }
)

ALL_TABLES = frozenset(METADATA.tables)


def table(name: str) -> Table:
    return METADATA.tables[name]


def test_every_table_in_the_plan_exists() -> None:
    """The baseline is the whole design, not a first slice of it."""
    assert ALL_TABLES == {
        "users",
        "anonymous_sessions",
        "research_sessions",
        "research_versions",
        "sources",
        "evidence",
        "claims",
        "claim_evidence",
        "conflicts",
        "conflict_evidence",
        "report_sections",
        "visualizations",
        "visualization_evidence",
        "conversation_messages",
        "message_evidence",
        "uploads",
        "upload_chunks",
        "exports",
        "activity_events",
        "research_runs",
        "run_steps",
        "tool_invocations",
    }


@pytest.mark.parametrize("name", sorted(ALL_TABLES))
def test_every_table_has_a_primary_key(name: str) -> None:
    assert table(name).primary_key.columns, f"{name} has no primary key"


@pytest.mark.parametrize("name", sorted(ALL_TABLES))
def test_every_timestamp_carries_a_timezone(name: str) -> None:
    """A naive timestamp discards the only thing that makes cross-source time
    comparison valid (`REQ-EVID-004`, `REQ-TOOL-007 AC-1`)."""
    for column in table(name).columns:
        if isinstance(column.type, DateTime):
            assert column.type.timezone, f"{name}.{column.name} is not timestamptz"


@pytest.mark.parametrize("name", sorted(VERSION_SCOPED_TABLES))
def test_version_scoped_tables_carry_and_index_version_id(name: str) -> None:
    """Loading a workspace is a small number of `WHERE version_id = $1` reads
    (implementation plan section 4.3), which is only true if the index is there."""
    columns = table(name).columns
    assert "version_id" in columns, f"{name} is version-scoped but has no version_id"

    indexed = any(
        "version_id" in {column.name for column in index.columns}
        for index in table(name).indexes
    )
    assert indexed, f"{name}.version_id is not indexed"


@pytest.mark.parametrize("name", sorted(ALL_TABLES))
def test_no_column_is_an_unbounded_varchar(name: str) -> None:
    """`text` unless a length is a real constraint. The only bounded column in
    the schema is `evidence.currency`, which is ISO 4217 and genuinely three
    characters."""
    for column in table(name).columns:
        rendered = column.type.compile(dialect=postgresql.dialect())
        if rendered.startswith("VARCHAR"):
            assert (name, column.name) == ("evidence", "currency")
            assert rendered == "VARCHAR(3)"


def test_enums_store_values_not_member_names() -> None:
    """`values_callable` is what keeps the stored label the wire value.

    Without it Postgres would hold `IN_PROGRESS` while every requirement,
    fixture and API payload says `in_progress`.
    """
    assert pg_enum(ClaimType, "claim_type").enums == [
        "fact",
        "analysis",
        "forecast",
        "uncertainty",
    ]


@pytest.mark.parametrize("name", sorted(ALL_TABLES))
def test_enum_columns_are_native_postgres_types(name: str) -> None:
    """A native enum makes an invalid state unrepresentable at the storage layer,
    which matters most for the columns the validation gate reads."""
    for column in table(name).columns:
        if isinstance(column.type, Enum):
            assert column.type.native_enum, f"{name}.{column.name} is not a native enum"
            assert column.type.name, f"{name}.{column.name} has an unnamed enum type"


def test_constraint_naming_convention_is_applied() -> None:
    """Deterministic names are what make an autogenerated diff about the schema
    rather than about naming noise."""
    assert METADATA.naming_convention == NAMING_CONVENTION
    assert table("research_sessions").primary_key.name == "pk_research_sessions"


def test_ownership_is_exclusive_by_constraint() -> None:
    """A research session has exactly one owner, enforced by the database.

    This is what makes an ownerless session unrepresentable, and why the
    anonymous identity half of `OPEN-17` could not wait for Phase 5.
    """
    checks = {
        constraint.name
        for constraint in table("research_sessions").constraints
        if constraint.name
    }
    assert "ck_research_sessions_one_owner" in checks


def test_forecast_claims_require_assumptions_by_constraint() -> None:
    """`REQ-SYNTH-009` at the storage layer: a forecast without stated
    assumptions is a guess, and the database refuses to hold one."""
    checks = {
        constraint.name
        for constraint in table("claims").constraints
        if constraint.name
    }
    assert "ck_claims_forecast_needs_assumptions" in checks


def test_deduplication_is_scoped_to_a_version() -> None:
    """`REQ-EVID-006` deduplicates within a version, never across versions: the
    same URL fetched for a later version is a different record with a different
    retrieval timestamp (`REQ-VER-003 AC-2`)."""
    unique_columns = [
        tuple(column.name for column in constraint.columns)
        for constraint in table("sources").constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    ]
    assert ("version_id", "url_normalized") in unique_columns
